services:
  backend:
    build: .
    container_name: backend-node
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=devopsahmed
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devopsahmed
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
